name: React CI

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.20.1]

    steps:
      - uses: actions/checkout@v1
      - name: install
        run: npm install
      - name: build
        run: CI='false' npm run build
      - name: test
        run: npm test
